apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kong
spec:
  interval: 24h
  url: https://charts.konghq.com
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kong-ingress
spec:
  interval: 24h
  chart:
    spec:
      chart: ingress
      version: "0.x"
      sourceRef:
        kind: HelmRepository
        name: kong
        namespace: kong
