services:
  emqx:
    image: emqx/emqx:5.8.0
    ports:
      - "1883:1883"
      - "18083:18083"
    volumes:
      - emqx-data:/opt/emqx/data
      - emqx-log:/opt/emqx/log
    environment:
      EMQX_NODE__NAME: emqx@127.0.0.1
      EMQX_DASHBOARD__DEFAULT_USERNAME: ${EMQX_DASHBOARD__DEFAULT_USERNAME:?}
      EMQX_DASHBOARD__DEFAULT_PASSWORD: ${EMQX_DASHBOARD__DEFAULT_PASSWORD:?}

volumes:
  emqx-data:
  emqx-log:
