include:
  - ./docker/caddy/compose.yaml
  - ./docker/dex/compose.yaml
  - ./docker/emqx/compose.yaml
  - ./docker/gitea/compose.yaml
  - ./docker/minio/compose.yaml
  - ./docker/mongo/compose.yaml
  - ./docker/openobserve/compose.yaml
  - ./docker/postgres/compose.yaml
  - ./docker/redis/compose.yaml

services:
  frontend:
    build: ./src/frontend
