apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: minio
  namespace: flux-system
spec:
  interval: 24h
  url: https://github.com/minio/operator
  ref:
    tag: v6.0.3
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: minio-operator
  namespace: flux-system
spec:
  interval: 24h
  path: .
  prune: true
  sourceRef:
    kind: GitRepository
    name: minio
