apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cnpg
  namespace: cnpg-system
spec:
  interval: 24h
  url: https://cloudnative-pg.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg-operator
  namespace: cnpg-system
spec:
  interval: 24h
  chart:
    spec:
      chart: cloudnative-pg
      version: "0.x"
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: cnpg-system
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg-cluster
  namespace: cnpg-database
spec:
  dependsOn:
  - name: cnpg-operator
    namespace: cnpg-system
  interval: 24h
  chart:
    spec:
      chart: cluster
      version: "0.x"
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: cnpg-system
