services:
  caddy:
    image: caddy:2.8-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../../certs:/root/certs
      - ./Caddyfile:/etc/caddy/Caddyfile
    environment:
      LOAD_BALANCER_IP: ${LOAD_BALANCER_IP:?}
    networks:
      - minikube
      - default

networks:
  minikube:
    external: true
