apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gateway-api
  namespace: flux-system
spec:
  interval: 24h
  url: https://github.com/kubernetes-sigs/gateway-api
  ref:
    tag: v1.1.0
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-api-crd
  namespace: flux-system
spec:
  interval: 24h
  path: ./config/crd/standard
  prune: true
  sourceRef:
    kind: GitRepository
    name: gateway-api
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kong-ingress
  namespace: flux-system
spec:
  dependsOn:
  - name: gateway-api-crd
  interval: 24h
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/infra/kong-ingress
  prune: true
  healthChecks:
  - apiVersion: apps/v1
    kind: Deployment
    name: kong-ingress-controller
    namespace: kong
  - apiVersion: apps/v1
    kind: Deployment
    name: kong-ingress-gateway
    namespace: kong
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: deployment
  namespace: flux-system
spec:
  dependsOn:
  - name: kong-ingress
  interval: 1m0s
  path: ./kubernetes/environments/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
