services:
  server:
    build: .
    ports:
      - "8000:80"
    environment:
      - PORT=80
      - OTEL_SERVICE_NAME=sandbox
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://openobserve:5081
      - OTEL_EXPORTER_OTLP_HEADERS=Authorization=Basic YWRtaW5AZG9tYWluLmNvbTphZG1pbg==,organization=default,stream-name=default
  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:v0.10.7-rc4
    ports:
      - "5080:5080"
      - "5081:5081"
    environment:
      - ZO_ROOT_USER_EMAIL=admin@domain.com
      - ZO_ROOT_USER_PASSWORD=admin
