services:
  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:v0.12.1
    ports:
      - "5080:5080"
      - "5081:5081"
    volumes:
      - openobserve:/data
    environment:
      - ZO_DATA_DIR=/data
      - ZO_ROOT_USER_EMAIL=${ZO_ROOT_USER_EMAIL:?}
      - ZO_ROOT_USER_PASSWORD=${ZO_ROOT_USER_PASSWORD:?}

volumes:
  openobserve:
