apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: http-route
spec:
  parentRefs:
  - kind: Gateway
    name: gateway
  rules:
  - backendRefs:
    - name: frontend
      port: 80
