apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../apps
- http-route.yaml
- gateway.yaml

transformers:
- |-
  apiVersion: builtin
  kind: NamespaceTransformer
  metadata:
    name: namespace-transformer
    namespace: dev
  unsetOnly: true

images:
- name: frontend-image
  newName: gitea.app.home.lab/homedium/frontend
  newTag: "0.0.0"
