apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
- namespace.yaml
- ../../apps
- http-route.yaml
- gateway.yaml
images:
- name: frontend-image
  newName: gitea.app.home.lab/homedium/frontend
  newTag: "0.0.0"
