services:
  minio:
    image: minio/minio:RELEASE.2024-09-09T16-59-28Z
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:?}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:?}
      MINIO_BROWSER_REDIRECT_URL: https://minio.app.home.lab/console

volumes:
  minio:
