services:
  otel-collector:
    image: otel/opentelemetry-collector:0.110.0
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
    volumes:
      - ./config.yaml:/etc/otelcol/config.yaml
    environment:
      OPENOBSERVE_AUTH_HEADER: ${OPENOBSERVE_AUTH_HEADER:?}
