receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - http://*
            - https://*

processors:
  batch:

exporters:
  otlphttp/openobserve:
    endpoint: http://openobserve:5080/api/default/
    headers:
      Authorization: ${env:OPENOBSERVE_AUTH_HEADER}
      stream-name: default
  otlp/openobserve:
      endpoint: openobserve:5081
      headers:
        Authorization: ${env:OPENOBSERVE_AUTH_HEADER}
        organization: default
        stream-name: default
      tls:
        insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/openobserve]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/openobserve]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/openobserve]
